# AUTOSTART

exec-once = waybar & hyprpaper & pipewire-pulse
exec-once = swayidle \
  timeout 300 'hyprlock -f' \
  timeout 600 'hyprlock -f && hyprctl dispatch dpms off' \
  resume 'hyprctl dispatch dpms on'
