-- AUTOSTART

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar & hyprpaper & pipewire-pulse")
    hl.exec_cmd("swayidle   timeout 300 'hyprlock -f'   timeout 600 'hyprlock -f && hyprctl dispatch dpms off'   resume 'hyprctl dispatch dpms on'")
end)

