--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland

terminal = "kitty"
fileManager = "nautilus"
menu = "hyprlauncher"
browser = "firefox"
