--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland

terminal = "kitty"
fileManager = "kitty mc"
menu = "~/.config/hypr/program_exec_scripts/wofi.sh"
browser = "firefox"
