-- ENVIRONMENT VARIABLES

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

MAIN_SCALING=2

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

hl.env("HYPRSHOT_DIR", "Pictures/Screenshots")

hl.env("GDK_SCALE", MAIN_SCALING)
