-- ENVIRONMENT VARIABLES

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("OZONE_PLATFORM", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("HYPRSHOT_DIR", "$HOME/Pictures/Screenshots")

hl.env("GDK_SCALE", "$MAIN_SCALING")
hl.env("QT_SCALE_FACTOR", "$AMIN_SCALING")
