exec-once = /home/jbxoid/.config/system_sounds/play_sound.sh logon

# Test error sound
bind = SUPER SHIFT, E, exec, /home/jbxoid/.config/system_sounds/play_sound.sh error
exec-once = /home/jbxoid/.config/system_sounds/notify_sound_listener.sh
