# ~/.config/hypr/hyprtoolkit.conf

# --- Font Settings ---
font_family = "Adwaita Sans"   # Or any installed font, e.g., "JetBrains Mono Nerd Font"
font_wegiht = 900
font_size = 14                 # Default is 11

base = rgba(242424FF)            # slightly lighter base
text = rgba(FFFFFFFF)            # pure white main text
bright_text = rgba(FFDEDEFF)     # warm white highlight
accent = rgba(FFFFFFFF)          # white accent (e.g. selected item)
accent_secondary = rgba(AAAAAAFF) # soft grey second accent
rounding_large = 10
rounding_small = 5
icon_theme = Papirus
