-- MONITORS
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local MAIN_SCALING = 2

hl.monitor({
    output = "",
    mode = "3840x2160@144",
    position = "auto",
    scale = MAIN_SCALING,
})

