--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrules that are useful

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    -- Ignore maximize requests from all apps. You'll probably like this.
    suppress_event = "maximize",
})

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    -- Fix some dragging issues with XWayland
    no_focus = true,
})

hl.window_rule({
    name = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = "20 monitor_h-120",
    float = true,
})

hl.window_rule({
    match = {
        class = "piper",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "openrgb",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "pavucontrol",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "Calculator",
    },
    float = true,
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
    -- Hyprland-run windowrule
    -- Window rules for floating windows
})

