general {
    grab_focus = false
}

# Enable/disable caching of often-used entries
cache {
    enabled = true
}

# Customize finders like Desktop, Math, or Unicode
finders {
    default_finder = desktop
    desktop_icons = true
    math_prefix = =
    unicode_prefix = .
}
