# My Hyprland config :)

               ####    #### 
               ####    ####
               ####    ####

               ############
               ############
               ############
                ##########

  #   #	 #####  #####  #####  #####  #   #
  ## ##  #   #    #    #   #    #     # # 
  # # #  #####    #    ####     #      #
  #   #  #   #    #    #  #     #     # #
  #   #  #   #    #    #   #  #####  #   #


# Monitor configuration
source = ~/.config/hypr/monitor.conf

# Default programs
source = ~/.config/hypr/defaultProgs.conf

# Autostart
source = ~/.config/hypr/autostart.conf

# Env configuration
source = ~/.config/hypr/env.conf

# Appearance configuration
source = ~/.config/hypr/appearance.conf

# Keybinds configuration
source = ~/.config/hypr/keybinds.conf

# Input configuration
source = ~/.config/hypr/input.conf

# Windows configuration. Not OS. Windows is shitty microslop product...
source = ~/.config/hypr/windows.conf

# Splash config
source = ~/.config/hypr/splash.conf
