# Font
font_family      Adwaita Sans
bold_font         auto
italic_font       auto
font_size         14.0

# Theme (Dark)
foreground        #ffffff
background        #181818
selection_foreground #181818
selection_background #ffffff

# Window
hide_window_decorations yes
window_padding_width 12

# Tab bar
tab_bar_style     powerline
active_tab_foreground #181818
active_tab_background #ffffff

# Cursor
cursor_shape      block
cursor_blink_interval 0.5
cursor_trail 5


# Misc
confirm_os_window_close 0
